<?php

namespace backend\models\forms;

use yii\base\DynamicModel;
use yii\db\ActiveRecord;
use yii\db\Exception;
use common\traits\ModelTrait;

/**
 * Class PriceForm
 *
 */
class PriceForm extends \yii\base\Model
{
    use ModelTrait;

    public $title;
    public $description;
    public $article;

    public function rules()
    {
        return [
            [['title', 'article', 'description'], 'required']
        ];
    }

    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors); // TODO: Change the autogenerated stub
    }

    public function load($data, $formName = null)
    {
        return parent::load($data, $formName); // TODO: Change the autogenerated stub
    }
}